services:
  airflow-init:
    image: airflow_own
    container_name: airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqldb://root:Bit_20092414@sh-cynosdbmysql-grp-jmhb3loc.sql.tencentcdb.com:22185/airflow
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Shanghai
    volumes:
      - logs:/opt/airflow/logs
    entrypoint: ["bash", "-c", "airflow db check-migrations || airflow db init && airflow users list | grep -q admin || airflow users create --username admin --password freeforhome --firstname Fang --lastname Yongchao --role Admin --email yongchao.fang@outlook.com"]

  airflow-webserver:
    image: airflow_own
    container_name: airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqldb://root:Bit_20092414@sh-cynosdbmysql-grp-jmhb3loc.sql.tencentcdb.com:22185/airflow
      - AIRFLOW__WEBSERVER__WORKERS=4
      - AIRFLOW__WEBSERVER__PORT=8080
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Shanghai
    ports:
      - "8080:8080"
    volumes:
      - logs:/opt/airflow/logs
    entrypoint: ["bash", "-c", "airflow webserver"]
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    image: airflow_own
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqldb://root:Bit_20092414@sh-cynosdbmysql-grp-jmhb3loc.sql.tencentcdb.com:22185/airflow
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Shanghai
      - PYTHONPATH=/opt/airflow
    volumes:
      - logs:/opt/airflow/logs
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
    entrypoint: ["bash", "-c", "airflow scheduler"]
    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  logs:
