from sqlalchemy import Column, String, DECIMAL, DateTime, BLOB
from app.database.mysql import Base
from app.services.update_strategy import UpdateStrategy


class Positions(Base):
    __scope__ = 'crypto'
    __tablename__ = 'positions'

    adl = Column(String(255), nullable=True, comment='ADL')
    avail_pos = Column(DECIMAL(38, 16), nullable=True, comment='可用仓位')
    avg_px = Column(DECIMAL(38, 16), nullable=True, comment='平均价格')
    base_bal = Column(String(255), nullable=True, comment='基础余额')
    base_borrowed = Column(String(255), nullable=True, comment='基础借款')
    base_interest = Column(String(255), nullable=True, comment='基础利息')
    be_px = Column(String(255), nullable=True, comment='BE 价格')
    biz_ref_id = Column(String(255), nullable=True, comment='业务参考 ID')
    biz_ref_type = Column(String(255), nullable=True, comment='业务参考类型')
    c_time = Column(DateTime, nullable=True, comment='创建时间')
    ccy = Column(String(255), primary_key=True, nullable=True, comment='币种')
    cl_spot_in_use_amt = Column(String(255), nullable=True, comment='使用中的现货金额')
    close_order_algo = Column(BLOB, nullable=True, comment='关闭订单算法')
    delta_bs = Column(String(255), nullable=True, comment='Delta BS')
    delta_pa = Column(String(255), nullable=True, comment='Delta PA')
    fee = Column(DECIMAL(38, 16), nullable=True, comment='费用')
    funding_fee = Column(DECIMAL(38, 16), nullable=True, comment='资金费用')
    gamma_bs = Column(DECIMAL(38, 16), nullable=True, comment='Gamma BS')
    gamma_pa = Column(DECIMAL(38, 16), nullable=True, comment='Gamma PA')
    idx_px = Column(DECIMAL(38, 16), nullable=True, comment='指数价格')
    imr = Column(DECIMAL(38, 16), nullable=True, comment='初始保证金率')
    inst_id = Column(String(255), primary_key=True, nullable=True, comment='产品 ID')
    inst_type = Column(String(255), nullable=True, comment='产品类型')
    interest = Column(DECIMAL(38, 16), nullable=True, comment='利息')
    last = Column(DECIMAL(38, 16), nullable=True, comment='最后价格')
    lever = Column(DECIMAL(38, 16), nullable=True, comment='杠杆')
    liab = Column(DECIMAL(38, 16), nullable=True, comment='负债')
    liab_ccy = Column(String(255), nullable=True, comment='负债币种')
    liq_penalty = Column(DECIMAL(38, 16), nullable=True, comment='清算罚金')
    liq_px = Column(DECIMAL(38, 16), nullable=True, comment='清算价格')
    margin = Column(DECIMAL(38, 16), nullable=True, comment='保证金')
    mark_px = Column(DECIMAL(38, 16), nullable=True, comment='标记价格')
    max_spot_in_use_amt = Column(DECIMAL(38, 16), nullable=True, comment='使用中的最大现货金额')
    mgn_mode = Column(String(255), nullable=True, comment='保证金模式')
    mgn_ratio = Column(DECIMAL(38, 16), nullable=True, comment='保证金率')
    mmr = Column(DECIMAL(38, 16), nullable=True, comment='维护保证金率')
    notional_usd = Column(DECIMAL(38, 16), nullable=True, comment='名义金额（USD）')
    opt_val = Column(DECIMAL(38, 16), nullable=True, comment='期权价值')
    pending_close_ord_liab_val = Column(DECIMAL(38, 16), nullable=True, comment='待关闭订单负债价值')
    pnl = Column(DECIMAL(38, 16), nullable=True, comment='损益')
    pos = Column(DECIMAL(38, 16), nullable=True, comment='仓位')
    pos_ccy = Column(String(255), nullable=True, comment='仓位币种')
    pos_id = Column(String(255), nullable=True, comment='仓位 ID')
    pos_side = Column(String(255), nullable=True, comment='仓位方向')
    quote_bal = Column(DECIMAL(38, 16), nullable=True, comment='报价余额')
    quote_borrowed = Column(DECIMAL(38, 16), nullable=True, comment='借入的报价币种')
    quote_interest = Column(DECIMAL(38, 16), nullable=True, comment='报价利息')
    realized_pnl = Column(DECIMAL(38, 16), nullable=True, comment='已实现损益')
    spot_in_use_amt = Column(DECIMAL(38, 16), nullable=True, comment='使用中的现货金额')
    spot_in_use_ccy = Column(String(255), nullable=True, comment='使用中的现货币种')
    theta_bs = Column(DECIMAL(38, 16), nullable=True, comment='Theta BS')
    theta_pa = Column(DECIMAL(38, 16), nullable=True, comment='Theta PA')
    trade_id = Column(String(255), nullable=True, comment='交易 ID')
    u_time = Column(DateTime, nullable=True, comment='更新时间')
    upl = Column(DECIMAL(38, 16), nullable=True, comment='未实现损益')
    upl_last_px = Column(DECIMAL(38, 16), nullable=True, comment='未实现损益（最新价格）')
    upl_ratio = Column(DECIMAL(38, 16), nullable=True, comment='未实现损益比率')
    upl_ratio_last_px = Column(DECIMAL(38, 16), nullable=True, comment='未实现损益比率（最新价格）')
    usd_px = Column(DECIMAL(38, 16), nullable=True, comment='美元价格')
    vega_bs = Column(DECIMAL(38, 16), nullable=True, comment='Vega BS')
    vega_pa = Column(DECIMAL(38, 16), nullable=True, comment='Vega PA')

    update_strategy = UpdateStrategy.FULL

    def __repr__(self):
        return f"<Positions(inst_id='{self.inst_id}', pos_id='{self.pos_id}')>"
