from funcs.synchronous.bills_history import synchronous_bills_history
from funcs.synchronous.instruments import synchronous_instruments
from funcs.synchronous.fills_history import synchronous_fills_history
from funcs.synchronous.withdraw_history import synchronous_withdraw_history
from funcs.synchronous.deposit_history import synchronous_deposit_history
from funcs.synchronous.mark_price import synchronous_mark_price