name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2 

      - name: Deploy to Server
        uses: fanggong/rsync-deploy@main
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 
          ARGS: -avz --delete
          SERVER_PORT: "22"
          FOLDER: ./
          SERVER_IP: ${{ secrets.SSH_HOST }} 
          USERNAME: ${{ secrets.SSH_USERNAME }} 
          SERVER_DESTINATION: /srv/feishu/

      - name: Update environment
        uses: fanggong/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /srv/feishu
            cp /root/config.yml /srv/feishu/config.yml
            conda activate feishu
            conda env update --file environment.yml --prune
            set +e
            pkill -f "run.py" > /dev/null 2>&1
            set -e
            nohup python3 run.py > run.log 2>&1 &